"""Inclusao_campo_respondido_na_tabela_contato

Revision ID: 36882577d602
Revises: 5ae9ef4243a6
Create Date: 2025-01-03 12:34:02.455077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36882577d602'
down_revision = '5ae9ef4243a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
